config/routes.rb
Rails.application.routes.draw do
  resources :rdvms
  resources :pets
  resources :clients
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#            user_session POST   /users/sign_in(.:format)       devise/sessions#create
#    destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#       new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#      edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#           user_password PATCH  /users/password(.:format)      devise/passwords#update
#                         PUT    /users/password(.:format)      devise/passwords#update
#                         POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#   new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#  edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#       user_registration PATCH  /users(.:format)               devise/registrations#update
#                         PUT    /users(.:format)               devise/registrations#update
#                         DELETE /users(.:format)               devise/registrations#destroy
#                         POST   /users(.:format)               devise/registrations#create

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/models/rdvm.rb
class Rdvm < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :address, :city, :state, :zip, :email, :sec_email, :phone, :sec_phone, :vet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :weight, :species, :breed, :client_id, :user_id)
    end
end

app/controllers/rdvms_controller.rb
class RdvmsController < ApplicationController
  before_action :set_rdvm, only: [:show, :edit, :update, :destroy]

  # GET /rdvms
  # GET /rdvms.json
  def index
    @rdvms = Rdvm.all
  end

  # GET /rdvms/1
  # GET /rdvms/1.json
  def show
  end

  # GET /rdvms/new
  def new
    @rdvm = Rdvm.new
  end

  # GET /rdvms/1/edit
  def edit
  end

  # POST /rdvms
  # POST /rdvms.json
  def create
    @rdvm = Rdvm.new(rdvm_params)

    respond_to do |format|
      if @rdvm.save
        format.html { redirect_to @rdvm, notice: 'Rdvm was successfully created.' }
        format.json { render :show, status: :created, location: @rdvm }
      else
        format.html { render :new }
        format.json { render json: @rdvm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rdvms/1
  # PATCH/PUT /rdvms/1.json
  def update
    respond_to do |format|
      if @rdvm.update(rdvm_params)
        format.html { redirect_to @rdvm, notice: 'Rdvm was successfully updated.' }
        format.json { render :show, status: :ok, location: @rdvm }
      else
        format.html { render :edit }
        format.json { render json: @rdvm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rdvms/1
  # DELETE /rdvms/1.json
  def destroy
    @rdvm.destroy
    respond_to do |format|
      format.html { redirect_to rdvms_url, notice: 'Rdvm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rdvm
      @rdvm = Rdvm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rdvm_params
      params.require(:rdvm).permit(:first_name, :last_name, :clinic_name, :clinic_address, :city, :state, :zip, :pref_contact, :phone, :email, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/rdvms_helper.rb
module RdvmsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :client_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :client_last_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :client_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :client_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :client_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :client_zip %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email %>
  </div>

  <div class="field">
    <%= form.label :sec_email %>
    <%= form.text_field :sec_email, id: :client_sec_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :client_phone %>
  </div>

  <div class="field">
    <%= form.label :sec_phone %>
    <%= form.text_field :sec_phone, id: :client_sec_phone %>
  </div>

  <div class="field">
    <%= form.label :vet_id %>
    <%= form.number_field :vet_id, id: :client_vet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Sec email</th>
      <th>Phone</th>
      <th>Sec phone</th>
      <th>Vet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.address %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>
        <td><%= client.email %></td>
        <td><%= client.sec_email %></td>
        <td><%= client.phone %></td>
        <td><%= client.sec_phone %></td>
        <td><%= client.vet_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Sec email:</strong>
  <%= @client.sec_email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Sec phone:</strong>
  <%= @client.sec_phone %>
</p>

<p>
  <strong>Vet:</strong>
  <%= @client.vet_id %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevisingClosure</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pet_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :pet_age %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight, id: :pet_weight %>
  </div>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species, id: :pet_species %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed, id: :pet_breed %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.number_field :client_id, id: :pet_client_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :pet_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Species</th>
      <th>Breed</th>
      <th>Client</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.species %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.client_id %></td>
        <td><%= pet.user_id %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Species:</strong>
  <%= @pet.species %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Client:</strong>
  <%= @pet.client_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @pet.user_id %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/rdvms/_form.html.erb
<%= form_with(model: rdvm, local: true) do |form| %>
  <% if rdvm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rdvm.errors.count, "error") %> prohibited this rdvm from being saved:</h2>

      <ul>
      <% rdvm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :rdvm_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :rdvm_last_name %>
  </div>

  <div class="field">
    <%= form.label :clinic_name %>
    <%= form.text_field :clinic_name, id: :rdvm_clinic_name %>
  </div>

  <div class="field">
    <%= form.label :clinic_address %>
    <%= form.text_field :clinic_address, id: :rdvm_clinic_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :rdvm_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :rdvm_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :rdvm_zip %>
  </div>

  <div class="field">
    <%= form.label :pref_contact %>
    <%= form.text_field :pref_contact, id: :rdvm_pref_contact %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :rdvm_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :rdvm_email %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :rdvm_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rdvms/edit.html.erb
<h1>Editing Rdvm</h1>

<%= render 'form', rdvm: @rdvm %>

<%= link_to 'Show', @rdvm %> |
<%= link_to 'Back', rdvms_path %>

app/views/rdvms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rdvms</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Clinic name</th>
      <th>Clinic address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Pref contact</th>
      <th>Phone</th>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rdvms.each do |rdvm| %>
      <tr>
        <td><%= rdvm.first_name %></td>
        <td><%= rdvm.last_name %></td>
        <td><%= rdvm.clinic_name %></td>
        <td><%= rdvm.clinic_address %></td>
        <td><%= rdvm.city %></td>
        <td><%= rdvm.state %></td>
        <td><%= rdvm.zip %></td>
        <td><%= rdvm.pref_contact %></td>
        <td><%= rdvm.phone %></td>
        <td><%= rdvm.email %></td>
        <td><%= rdvm.user_id %></td>
        <td><%= link_to 'Show', rdvm %></td>
        <td><%= link_to 'Edit', edit_rdvm_path(rdvm) %></td>
        <td><%= link_to 'Destroy', rdvm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rdvm', new_rdvm_path %>

app/views/rdvms/new.html.erb
<h1>New Rdvm</h1>

<%= render 'form', rdvm: @rdvm %>

<%= link_to 'Back', rdvms_path %>

app/views/rdvms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @rdvm.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @rdvm.last_name %>
</p>

<p>
  <strong>Clinic name:</strong>
  <%= @rdvm.clinic_name %>
</p>

<p>
  <strong>Clinic address:</strong>
  <%= @rdvm.clinic_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @rdvm.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @rdvm.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @rdvm.zip %>
</p>

<p>
  <strong>Pref contact:</strong>
  <%= @rdvm.pref_contact %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @rdvm.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @rdvm.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @rdvm.user_id %>
</p>

<%= link_to 'Edit', edit_rdvm_path(@rdvm) %> |
<%= link_to 'Back', rdvms_path %>